name: CI/CD for React App

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Start a static file server (optional)
      - name: Serve Static Files
        run: |
          npm install -g http-server
          http-server ./public -p 8080 &
          sleep 3

      # Run tests
      - name: Run tests
        run: |
          echo "Running Tests..."
          npm test -- --verbose || (echo "Tests failed!" && exit 1)
