# This workflow builds, tests, and pushes a Docker image for a React app

name: CI/CD for React App

on:
  push:
    branches: [ "master", "main" ] # Trigger on push to master or main
  pull_request:
    branches: [ "master", "main" ] # Trigger on pull request to master or main

jobs:
  # Job 1: Build and Test React App
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16] # Define Node.js version

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Clean npm cache
      - name: Clean npm cache
        run: npm cache clean --force

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Set environment variables (if needed)
      - name: Set environment variables
        run: |
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env

      # Build React app with verbose logging
      - name: Build React app
        run: |
          echo "Starting Build..."
          npm run build || (echo "Build failed!" && exit 1)

      # Run tests with verbose output
      - name: Run tests with verbose logging
        run: |
          echo "Running Tests..."
          npm test -- --verbose || (echo "Tests failed!" && exit 1)
