# This workflow builds, tests, and pushes a Docker image for a React app

name: CI/CD for React App

on:
  push:
    branches: [ "master", "main" ] # Trigger on push to master or main
  pull_request:
    branches: [ "master", "main" ] # Trigger on pull request to master or main

jobs:
  # Job 1: Build and Test React App
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16] # Define Node.js version

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build React app
      - name: Build React app
        run: npm run build --if-present

      # Run tests
      - name: Run tests
        run: npm test

  # Job 2: Build and Push Docker Image
  build-and-push-docker:
    needs: build-and-test # Only run this job if build-and-test succeeds
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest .

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest
